name: CI/CD pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone external repo
      uses: actions/checkout@v2
    - name: Clone external repo
      uses: actions/checkout@v2
      with:
        repository: kairemor/helm-charts
        ref: main
        path: helm-charts
    
    - name: Get commit hash
      id: get_commit_hash
      run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

    - name: Build the Docker image
      run: docker build -t  ${{ secrets.DOCKERHUB_USERNAME }}/django-app:${{ steps.get_commit_hash.outputs.commit_hash }} .
    
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Push Docker image to DockerHub
      run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/django-app:${{ steps.get_commit_hash.outputs.commit_hash }}

    - name: Install yq
      run: |
        sudo add-apt-repository ppa:rmescandon/yq -y
        sudo apt-get update
        sudo apt-get install yq -y
      
    - name: Set image tag in values file
      run: |
        git config --global user.email "kairemor@gmail.com"
        git config --global user.name "Mor Kaire"
        cd helm-charts
        yq eval '.image.tag = "${{ steps.get_commit_hash.outputs.commit_hash }}"' -i values.yaml
        git add values.yaml
        git commit -m "Update image tag in values.yaml"
        git push https://${{ secrets.GIT_TOKEN }}@github.com/kairemor/helm-charts.git HEAD:main
