name: CI/CD pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get commit hash
      id: get_commit_hash
      run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

    - name: Build the Docker image
      run: docker build -t  ${{ secrets.DOCKERHUB_USERNAME }}/django-app:${{ steps.get_commit_hash.outputs.commit_hash }} .
    
    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Push Docker image to DockerHub
      run: docker push  ${{ secrets.DOCKERHUB_USERNAME }}/django-app:${{ steps.get_commit_hash.outputs.commit_hash }}

    - name: Install yq
      run: |
        sudo add-apt-repository ppa:rmescandon/yq -y
        sudo apt-get update
        sudo apt-get install yq -y

    - name: Update tag value in values.yaml file
      run: yq eval '.image.tag = "${{ steps.get_commit_hash.outputs.commit_hash }}"' -i helm_chart/values.yaml
      env:
        COMMIT_HASH: ${{ steps.get_commit_hash.outputs.commit_hash }}

    - name: Commit and push changes
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git config --local user.email "your-email@example.com"
        git config --local user.name "Your Name"
        if [ -n "$(git status --porcelain helm_chart/values.yaml)" ]; then
          git add helm_chart/values.yaml
          git commit -m "Update tag value in values.yaml"
          git push origin main
        fi